name: pybites
channels:
  - defaults
  - conda-forge
dependencies:
  - attrs=19.3.0
  - beautifulsoup4=4.8.2
  - bs4=4.8.2
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - coverage=5.1
  - cryptography=2.9.2
  - feedparser=5.2.1
  - Flask=1.1.2
  - idna=2.9
  - itsdangerous=1.1.0
  - Jinja2=2.11.2
  - joblib=0.15.1
  - MarkupSafe=1.1.1
  - more-itertools=8.3.0
  - nltk=3.4.5
  - numpy=1.18.4
  - packaging=20.4
  - pandas=1.0.3
  - pip=20.0.2
  - pluggy=0.13.1
  - py=1.8.1
  - pycparser=2.20
  - pyparsing=2.4.7
  - pytest=5.4.2
  - pytest-asyncio=0.12.0
  - pytest-cov=2.9.0
  - python=3.8.2
  - python-dateutil=2.8.1
  - pytz=2020.1
  - regex=2020.5.14
  - requests=2.23.0
  - six=1.15.0
  - soupsieve=2.0.1
  - textblob=0.15.3
  - tqdm=4.46.0
  - urllib3=1.25.9
  - wcwidth=0.1.9
  - Werkzeug=1.0.1
  - xlrd=1.2.0
  - pip:
    - gender-guesser==0.4.0
